language: ruby
rvm:
  - 2.4.2

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build --drafts
#  - bundle exec htmlproof ./_site

notifications:
  email: true
