title:            Mike Christianson
description:
logo:
disqus_shortname:
search:           false
# Change url to your domain. Leave localhost server or blank when working locally.
url:              //codeaweso.me
feed_url:         http://feeds.codeaweso.me/CodeAwesome
temp_feed_internal_url: http://codeaweso.me

# Owner/author information
owner:
  name:           Mike Christianson
  avatar:         avatar.jpg
  email:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        https://twitter.com/MikeCodeAwesome
  twitter_handle: MikeCodeAwesome
  facebook:
  github:         https://github.com/MikeChristianson
  stackexchange:  http://stackoverflow.com/users/527169/mike-christianson
  linkedin:       https://www.linkedin.com/in/mikechristianson
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+MikeChristianson

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-1465279-6
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Mike
    url: /
  - title: Contact Mike
    url: /contact/
  - title: Read the Blog
    url: /blog/
  - title: Why AZ?
    url: http://why.az
    external: true
  - title: PHX Software Book Club
    url: /phoenix-software-engineering-reading-group-at-gangplank/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Phoenix
highlighter: rouge
markdown:    kramdown
encoding:    utf-8

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
